Fix quantization and add preserve_order
seung-lab/DracoPy pull request #28
Opened 2022-04-05 10:50 UTC by zeruniverse

* add encoding option: preserve_order
* added corresponding test
* make quantization_bits default same as Draco (11)
* update quantizaion_bits range to match Draco (1-30)
* Fix range
* added documentation

2022-04-05 12:27 UTC, zeruniverse commented
========================================================== test session starts ===========================================================
platform linux -- Python 3.7.11, pytest-7.1.1, pluggy-1.0.0 -- /home/jeffery/miniconda3/bin/python
cachedir: .pytest_cache
rootdir: /tmp/DracoPy
plugins: anyio-3.4.0
collected 5 items                                                                                                                        

tests.py::test_decoding_and_encoding_mesh_file PASSED                                                                              [ 20%]
tests.py::test_decoding_and_encoding_mesh_file_integer_positions PASSED                                                            [ 40%]
tests.py::test_decoding_improper_file PASSED                                                                                       [ 60%]
tests.py::test_metadata PASSED                                                                                                     [ 80%]
tests.py::test_decoding_and_encoding_point_cloud_file PASSED                                                                       [100%]

=========================================================== 5 passed in 3.31s ============================================================

2022-04-05 12:30 UTC, zeruniverse commented
mesh encoding is around 20% faster.

2022-04-05 13:25 UTC, zeruniverse commented
Needs cherry-pick after #27 merged

2022-04-05 17:41 UTC, william-silversmith requested changes
Thank you for this lovely PR with multiple improvements! Just a few very minor points from reading the code. I'll try testing this with our setup.

2022-04-05 17:41 UTC, william-silversmith commented on Dockerfile
> +RUN /opt/python/cp36-cp36m/bin/pip3.6 install scikit-build twine numpy
This should use `oldest-supported-numpy` to ensure broad numpy ABI compatibility with the produced binary.

2022-04-05 17:41 UTC, william-silversmith commented on src/DracoPy.h
> +    if(integer_positions){
`if (integer_positions) {` <- spacing

2022-04-05 17:41 UTC, william-silversmith commented on src/DracoPy.pyx
> +    preserve_order=False, create_metadata=False
Place `preserve_order` at the end to preserve interface backwards compatibility (even though most people are probably using keywords).

2022-04-06 00:51 UTC, zeruniverse commented on src/DracoPy.h
> +    if(integer_positions){
@william-silversmith I found integer_position actually stores uint. Is this a bug? Should i change it to DT_INT32? Also, python float should be C double, currently it’s C float

2022-04-06 01:02 UTC, william-silversmith commented on src/DracoPy.h
> +    if(integer_positions){
No this isn't a bug though maybe it could be better named. This is required for compatibility with a program called [Neuroglancer](https://github.com/google/neuroglancer). We feed numpy arrays with float32s into here, not doubles. Perhaps other users may use it differently, but it's designed as a numpy-first tool.

2022-04-06 01:11 UTC, zeruniverse commented
If this is the case, better use np.unsignedinteger as type checking instead
of np.integer. See

https://numpy.org/doc/stable/reference/arrays.scalars.html?highlight=unsignedinteger#numpy.unsignedinteger

On Wed, Apr 6, 2022 at 9:02 AM William Silversmith ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In src/DracoPy.h
> <https://github.com/seung-lab/DracoPy/pull/28#discussion_r843376939>:
>
> > -      : draco::DataType::DT_FLOAT32;
> -
> -    const int pos_att_id = mb.AddAttribute(
> -      draco::GeometryAttribute::POSITION, 3, dtype
> -    );
> +    // @zeruniverse TriangleSoupMeshBuilder will cause problems when
> +    //    preserve_order=True due to vertices merging.
> +    //    In order to support preserve_order, we need to build mesh
> +    //    manually.
> +    draco::Mesh mesh; //Initialize a draco mesh
> +
> +    // Process vertices
> +    const size_t num_pts = points.size() / 3;
> +    mesh.set_num_points(num_pts);
> +    draco::GeometryAttribute positions_attr;
> +    if(integer_positions){
>
> No this isn't a bug though maybe it could be better named. This is
> required for compatibility with a program called Neuroglancer
> <https://github.com/google/neuroglancer>. We feed numpy arrays with
> float32s into here, not doubles. Perhaps other users may use it
> differently, but it's designed as a numpy-first tool.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/seung-lab/DracoPy/pull/28#discussion_r843376939>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABDO6NBLOLJUBVY6TCWANRLVDTPCDANCNFSM5SSK2FWA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-04-06 01:26 UTC, zeruniverse commented on src/DracoPy.h
> +    if(integer_positions){
Ok, so let’s keep float as is. For integer, i think current solution is not correct as all negative integers will be 0. We can do one of following:

1. only set integer_positions (rename it to uint_positions) to True when numpy object has dtype np.unsignedinteger (currently, it’s np.integer)
2. Set draco type INT32 instead of UINT32.

let me know what you think

2022-04-06 02:18 UTC, william-silversmith commented on src/DracoPy.h
> +    if(integer_positions){
Customizing the type to the signedness of the input is fine with me. That shouldn't raise any compatibility issues.

2022-04-06 03:18 UTC, zeruniverse commented on src/DracoPy.h
> +    if(integer_positions){
why not just `draco::DataType::DT_INT32`

2022-04-06 03:20 UTC, william-silversmith commented on src/DracoPy.h
> +    if(integer_positions){
Mainly fears of loss of precision and differing behavior than expected around zero. No matter what library I publish, someone finds a way to test the limits. ;)

2022-04-06 03:21 UTC, william-silversmith commented on src/DracoPy.h
> +    if(integer_positions){
Also, Neuroglancer explicitly expects a uint32_t

2022-04-06 03:41 UTC, zeruniverse commented on src/DracoPy.h
> +    if(integer_positions){
are you ok if I it only supports uint?

2022-04-06 04:07 UTC, zeruniverse commented on src/DracoPy.h
> +    if(integer_positions){
ok. Now it supports uint / int and float

2022-04-06 05:20 UTC, zeruniverse commented
@william-silversmith rebased and ready for final review & test & merge

2022-04-06 20:31 UTC, william-silversmith commented
I remeshed a volume using https://github.com/seung-lab/igneous and this update and it looks good. Thanks so much for your contribution!

2022-04-06 20:31 UTC, william-silversmith approved these changes

2022-04-06 20:31 UTC, william-silversmith commented on setup.py
>      author = 'Manuel Castro, William Silversmith :: Contributors :: Fatih Erol, Faru Nuri Sonmez',
You can add yourself here if desired.

2022-04-06 20:32 UTC, merged

2022-04-07 02:52 UTC, zeruniverse commented
No worries. I contributed also because I need those changes for my project. @william-silversmith could you do me a favor by uploading linux py3.10 package to PyPI? Currently it only has Windows py3.10 package https://pypi.org/project/DracoPy/1.1.0/#files

2022-04-07 02:53 UTC, zeruniverse commented on setup.py
>      author = 'Manuel Castro, William Silversmith :: Contributors :: Fatih Erol, Faru Nuri Sonmez',
Haha, i can do this after I make more contributions

2022-04-07 03:36 UTC, william-silversmith commented
Whoops, looks like I forgot to update the Github Action. I'm building them locally and will upload soon.

2022-04-07 03:43 UTC, william-silversmith commented
Done!

2022-04-07 03:47 UTC, zeruniverse commented
I saw it. Thanks

2025-02-28 01:29 UTC, afshawnlotfi commented
I feel like this should clearly be denoted somewhere that order is not preserved. I spent a sec trying to understand why an encoded -> decoded points didn't match