implement colors (#30)
seung-lab/DracoPy pull request #32
Opened 2022-08-08 04:48 UTC by zeruniverse

https://github.com/seung-lab/DracoPy/issues/30#issue-1240000941

Implement colors (N, K) uint8 values for encoding and decoding to support color / custom data encoding

2022-08-08 07:34 UTC, zeruniverse commented
@william-silversmith please help review.

- [x] build success with new version number
- [x] tests added and passed
- [x] README updated
- [ ] merged
- [ ] upload to pypi

2022-08-13 05:40 UTC, william-silversmith requested changes
Just a few minor points to clear up plus some justification for color being a uint8 only and 0 - 100 channels. Thank you for the submission!

2022-08-13 05:40 UTC, william-silversmith commented on src/DracoPy.h
> +      uint8_t* color_val = new uint8_t[colors_channel];
Good practice to always initialize these declarations. Otherwise garbage values will be hard to debug if something goes wrong.

2022-08-13 05:40 UTC, william-silversmith commented on src/DracoPy.h
> +    } else meshObject.colors_set = false;
House style is to always use braces around conditional statements (except ternary operators of course). This makes it difficult to screw up the addition of more lines.

2022-08-13 05:40 UTC, william-silversmith commented on src/DracoPy.pyx
> +__version__ = "1.1.2"
For a new feature, the minor version should be incremented. 1.2.0

2022-08-13 05:40 UTC, william-silversmith commented on src/DracoPy.pyx
> +        assert 1 <= colors_channel <= 100, "Number of color channels must be in range [1, 100]"
Can you point to documentation for this?

2022-08-13 05:40 UTC, william-silversmith commented on src/DracoPy.pyx
> +    cdef vector[uint8_t] colorsview
In the Draco repo, an example shows colors can be floating point. Are uint8 colors G or RGB? Can they be RGBA? What does a 100 channel color mean?

2022-08-13 07:06 UTC, zeruniverse commented
It’s actually a generalized idea for vertex attributes. Whether it’s RGB or
RGBA depends on calling method. Making it 100 upper limit so it won’t grow
too big. The problem of floating point is it will be quantized. But uint8
won’t

On Sat, Aug 13, 2022 at 1:40 PM William Silversmith <
***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Just a few minor points to clear up plus some justification for color
> being a uint8 only and 0 - 100 channels. Thank you for the submission!
> ------------------------------
>
> In src/DracoPy.h
> <https://github.com/seung-lab/DracoPy/pull/32#discussion_r945085561>:
>
> > @@ -122,6 +124,26 @@ namespace DracoFunctions {
>        meshObject.points.push_back(pos_val[2]);
>      }
>
> +    const int color_att_id = mesh->GetNamedAttributeId(draco::GeometryAttribute::COLOR);
> +    if (color_att_id >= 0) {
> +      meshObject.colors_set = true;
> +      const auto *const color_att = mesh->attribute(color_att_id);
> +      const int colors_channel = color_att->num_components();
> +      meshObject.colors.reserve(colors_channel * mesh->num_points());
> +      uint8_t* color_val = new uint8_t[colors_channel];
>
> Good practice to always initialize these declarations. Otherwise garbage
> values will be hard to debug if something goes wrong.
> ------------------------------
>
> In src/DracoPy.h
> <https://github.com/seung-lab/DracoPy/pull/32#discussion_r945085628>:
>
> > +      const auto *const color_att = mesh->attribute(color_att_id);
> +      const int colors_channel = color_att->num_components();
> +      meshObject.colors.reserve(colors_channel * mesh->num_points());
> +      uint8_t* color_val = new uint8_t[colors_channel];
> +      for (draco::PointIndex v(0); v < mesh->num_points(); ++v) {
> +        if (!color_att->ConvertValue<uint8_t>(color_att->mapped_index(v), colors_channel, color_val)) {
> +          meshObject.colors_set = false; // color decoding failed!
> +          break; // it already failed
> +        } else {
> +          for (int i = 0; i < colors_channel; ++i) {
> +            meshObject.colors.push_back(color_val[i]);
> +          }
> +        }
> +      }
> +      delete [] color_val;
> +    } else meshObject.colors_set = false;
>
> House style is to always use braces around conditional statements (except
> ternary operators of course). This makes it difficult to screw up the
> addition of more lines.
> ------------------------------
>
> In src/DracoPy.pyx
> <https://github.com/seung-lab/DracoPy/pull/32#discussion_r945086699>:
>
> > @@ -15,7 +15,7 @@ cimport numpy as np
>  import numpy as np
>
>
> -__version__ = "1.1.1"
> +__version__ = "1.1.2"
>
> For a new feature, the minor version should be incremented. 1.2.0
> ------------------------------
>
> In src/DracoPy.pyx
> <https://github.com/seung-lab/DracoPy/pull/32#discussion_r945087334>:
>
> > @@ -156,20 +170,31 @@ def encode(
>
>      cdef vector[float] pointsview = points.reshape((points.size,))
>      cdef vector[uint32_t] facesview
> +    cdef vector[uint8_t] colorsview
> +
> +    colors_channel = 0
> +    if colors is not None:
> +        assert np.issubdtype(colors.dtype, np.uint8), "Colors must be uint8"
> +        assert len(colors.shape) == 2, "Colors must be 2D"
> +        colors_channel = colors.shape[1]
> +        assert 1 <= colors_channel <= 100, "Number of color channels must be in range [1, 100]"
>
> Can you point to documentation for this?
> ------------------------------
>
> In src/DracoPy.pyx
> <https://github.com/seung-lab/DracoPy/pull/32#discussion_r945087424>:
>
> > @@ -156,20 +170,31 @@ def encode(
>
>      cdef vector[float] pointsview = points.reshape((points.size,))
>      cdef vector[uint32_t] facesview
> +    cdef vector[uint8_t] colorsview
>
> In the Draco repo, an example shows colors can be floating point. Are
> uint8 colors G or RGB? Can they be RGBA? What does a 100 channel color mean?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/seung-lab/DracoPy/pull/32#pullrequestreview-1071903061>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABDO6NHER67MHS5KHD6CWLDVY4YMVANCNFSM553W7U3A>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-08-13 14:44 UTC, zeruniverse commented on src/DracoPy.pyx
> +        assert 1 <= colors_channel <= 100, "Number of color channels must be in range [1, 100]"
This is a just a random number for upper limit. I changed it to 255, which is the upper limit of uint8_t size. I don't think this should exceed 255 in any case

2022-08-13 14:44 UTC, zeruniverse commented on src/DracoPy.pyx
> +__version__ = "1.1.2"
done

2022-08-13 14:44 UTC, zeruniverse commented on src/DracoPy.h
> +    } else meshObject.colors_set = false;
done

2022-08-13 14:51 UTC, zeruniverse commented on src/DracoPy.pyx
> +    cdef vector[uint8_t] colorsview
See comments below. It's actually an abstract color. Can be BGR, RGBA, L or anything that's attribute associated with vertices. I have changed 100 to 255, which is the upper limit of uint8_t. In my use case, the channel is always 4 (RGBA), but I just made it more general.

I'm implementing this in uint8_t so that it is consistent with [trimesh](https://trimsh.org/trimesh.visual.color.html#trimesh.visual.color.ColorVisuals.__init__), (a very popular) Python library I used for my need. And usually, colors are in uint8_t.

2022-08-13 14:55 UTC, zeruniverse commented on src/DracoPy.h
> +      uint8_t* color_val = new uint8_t[colors_channel];
Well, I don't think it's needed. Initialization to zero takes additional CPU time, and garbage values here are equivalent to zero values as my code does not expect the array being initialized.

2022-08-18 23:38 UTC, william-silversmith commented
Sorry for taking so long to get back to you, I was working on a paper and got distracted. This looks good to me!

2022-08-18 23:39 UTC, merged