Decode texture coordinates
seung-lab/DracoPy pull request #39
Opened 2023-03-03 10:15 UTC by denisri

After failing to locally merge PR #17 (which seems somewhat abandoned), I took from it just the needed code to decode texture coordinates. This PR is lighter and can be merged on the current master, but doesn't implement the encoding part.

2023-03-03 16:28 UTC, william-silversmith requested changes

2023-03-03 16:28 UTC, william-silversmith commented on src/DracoPy.pyx
> +            return np.array([], dtype=tex_coord_.dtype)
This array will have the wrong shape. It needs to be reshaped.

2023-03-03 18:17 UTC, denisri commented on src/DracoPy.pyx
> +            return np.array([], dtype=tex_coord_.dtype)
Interesting point (well, two points actually).
* Which shape is actually expected for texture corrdinates ?
   Using it this way, for a mesh with a texure with 2 coordinates per vertex, I actually get an array of shape `(NV, 2)` (where `NV` is the number of vertices). This is consistent with points or normals arrays which are `(NV, 3)` for instance. But here I get "flipped" coordinates (both coordinates are switched) compared to the initial non-draco-encoded mesh, but as I don't know Draco at all I am not sure whether it is expected or not, and why. Is it what you were pointing out ? And thus it is not really a "reshape", but I need to do: `tex_corrd[:, -1::-1]` to get back the expected coordinates. Should I include this operation in the `tex_coord` property here (and is there a reason for this ?) ?
* in the situation where there are no texture coords, here I return an empty array of shape `(0, )`. Maybe it's not the best and I shoudl return `None` instead, or an array of shape `(0, 0)` ?

2023-03-03 19:37 UTC, william-silversmith commented on src/DracoPy.pyx
> +            return np.array([], dtype=tex_coord_.dtype)
I think it makes sense to return the tex coordinates in the same order as the original model.

For the second point, I think it makes sense to return `None` if the model has no texture attribute, but if it is labeled as having one, then `(0,0)` would be preferred.

2023-03-04 17:05 UTC, denisri commented on src/DracoPy.pyx
> +            return np.array([], dtype=tex_coord_.dtype)
OK it now returns None when there are no texture coords. And testing again I don't find the coordinates inversions I had when testing at first. So I must have done something wrong, but it seems to work as expected now (otherwise there is something I don't understand)

2023-03-21 19:15 UTC, william-silversmith commented
Hi! I'm sorry, I've just been overwhelmed with various projects and the tests are broken on this repo. I need to fix them before I can release a new version. I will try to do this soon!

2023-03-26 00:49 UTC, william-silversmith commented
Hi! I think I've fixed the build process. Please just fix the merge conflic on DracoPy.cpp and we can get moving!

2023-03-27 14:05 UTC, merged